CESIMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('admin/', include('administrator.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('', include('main.urls')),
]

administrator/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'administrator'

urlpatterns = [
	path('posts/new/', PostCreateView.as_view(), name='post-create'),
	path('reports/new/', ReportCreateView.as_view(), name='report-create'),
	path('users/new/', UserCreateView.as_view(), name='user-create'),
	path('posts/', PostListView.as_view(), name='post-list'),
	path('posts/<int:pk>/', PostUpdateView.as_view(), name='post-update'),
	path('students/<int:pk>/', StudentUpdateView.as_view(), name='student-update'),
	path('posts/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
	path('students/<int:pk>/delete', StudentDeleteView.as_view(), name='student-delete'),
	path('staff/new/', StaffCreateView.as_view(), name='staff-create'),
	path('students/new/', StudentCreateView.as_view(), name='student-create'),
	path('staff/', StaffListView.as_view(), name='staff-list'),
	path('students/', StudentListView.as_view(), name='student-list'),
	path('sections/', SectionListView.as_view(), name='section-list'),
	path('reports/', ReportListView.as_view(), name='report-list'),
	path('users/', UserListView.as_view(), name='user-list'),
	path('staff/<int:pk>/', StaffDetailView.as_view(), name='staff-detail'),
	path('staff/<int:pk>/edit', StaffUpdateView.as_view(), name='staff-update'),
	path('reports/<int:pk>/edit', ReportUpdateView.as_view(), name='report-update'),
	path('users/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
	path('staff/<int:pk>/delete', StaffDeleteView.as_view(), name='staff-delete'),
	path('report/<int:pk>/delete', ReportDeleteView.as_view(), name='report-delete'),
	path('users/log/', LogEntryListView.as_view(), name='logentry-list'),
	path('', DashboardView.as_view(), name='dashboard'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'main'
urlpatterns = [
    path('news/', PostListView.as_view(), name='news'),
    path('news/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('', HomepageView.as_view(), name='home'),
    path('transparency/', home, name='pubreport-list'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from PIL import Image
from django.urls import reverse
from django.utils import timezone
import os

# Create your models here.
GENDER_CHOICES = (
	('M', 'Male'),
	('F', 'Female'),
)
class Term(models.Model):
	title = models.CharField(max_length=25)
	start_date = models.DateField()
	end_date = models.DateField()

	def __str__(self):
		return self.title

	class Meta:
		get_latest_by = "-start_date"

class Section(models.Model):
	GRADE_CHOICES = (
		('0', 'Kinder'),
		('1', 'I'),
		('2', 'II'),
		('3', 'III'),
		('4', 'IV'),
		('5', 'V'),
		('6', 'VI'),
	)
	class Meta:
		unique_together = ("grade_level", "name", "term")

	grade_level = models.CharField(choices=GRADE_CHOICES, max_length=1)
	name = models.CharField(max_length=25)
	term = models.ForeignKey(Term, on_delete=models.CASCADE)

	def __str__(self):
		return f'{ self.get_grade_level_display() } - { self.name }'

class Student(models.Model):
	first_name = models.CharField(max_length=25)
	last_name = models.CharField(max_length=25)
	middle_name = models.CharField(max_length=25, default=None, blank=True, null=True)

	lrn = models.CharField(max_length = 12, unique=True, null=True, blank=True, verbose_name='Learner Reference Number')
	section = models.ForeignKey(Section, on_delete=models.CASCADE)
	sex = models.CharField(max_length=1, choices=GENDER_CHOICES)
	birthdate = models.DateField()

	home_address = models.TextField(null=True, blank=True)
	guardian_name = models.CharField(max_length=140, null=True, blank=True)
	contact_number = models.CharField(max_length=13, null=True, blank=True)
	remarks = models.CharField(max_length=70, null=True, blank=True)

	def calculate_age(self):
		today = date.today()
		return today.year - self.birthdate.year - ((today.month, today.day) < (self.birthdate.month, self.birthdate.day))

	def get_absolute_url(self):
		return reverse('student-update', kwargs={'pk': self.pk})

	def __str__(self):
		return f'{self.last_name}, {self.first_name} {self.middle_name}'

class Staff(models.Model):
	STATUS_CHOICES = (
	('SG', 'Single'),
	('M', 'Married'),
	('D', 'Divorced'),
	('SE', 'Separated'),
	('W', 'Widowed'),
	)

	school_id = models.CharField(verbose_name='Employee ID', max_length=9, help_text="Please follow the following format: 12-345678")
	image = models.ImageField(default='staff/img/default.jpg', upload_to='staff/img')
	first_name = models.CharField(max_length=25)
	last_name = models.CharField(max_length=25)
	middle_name = models.CharField(blank=True, null=True, max_length=25)

	email_address = models.EmailField()
	contact_number = models.CharField(max_length=13)

	birthdate = models.DateField()
	sex = models.CharField(max_length=2, choices=GENDER_CHOICES)
	civil_status = models.CharField(max_length=9, choices=STATUS_CHOICES)

	position = models.CharField(max_length=100)
	salary = models.PositiveIntegerField()
	advisory_section = models.OneToOneField(Section, on_delete=models.CASCADE, null=True, blank=True)

	appointment_file = models.FileField(blank=True, null=True, upload_to='staff/appointment')
	pds_file = models.FileField(blank=True, null=True, upload_to='staff/pds', verbose_name='Personal Data Sheet')
	prc_license_file = models.FileField(blank=True, null=True, upload_to='staff/prc_license', verbose_name= 'PRC License Copy')
	saln_file = models.FileField(blank=True, null=True, upload_to='staff/saln_file', verbose_name='SALN Form')

	def calculate_age(self):
		today = date.today()
		return today.year - self.birthdate.year - ((today.month, today.day) < (self.birthdate.month, self.birthdate.day))

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

	def save(self):
		super().save()

		img = Image.open(self.image.path)

		if img.height > 200 or img.width > 200:
			output_size = (200, 200)
			img.thumbnail(output_size)
			img.save(self.image.path)

	def get_absolute_url(self):
		return reverse('staff-detail', kwargs={'pk': self.pk})

class Post(models.Model):
	title = models.CharField(max_length = 140)
	desc = models.TextField(verbose_name='Description')
	image = models.ImageField(upload_to='gallery/%Y/%m/%d')
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

	def get_absolute_url(self):
		return reverse('post-update', kwargs={'pk': self.pk})

	def __str__(self):
		return self.title

class Report(models.Model):
	title = models.CharField(max_length = 50)
	remarks = models.CharField(max_length= 30, blank=True, null=True)
	file = models.FileField(upload_to='reports/%Y/%m/%d')
	month_year = models.DateField(default=timezone.now)
	date_uploaded = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.title} - {self.month_year.strftime("%B %Y")}'

	def thumbnail(self):
		name, extension = os.path.splitext(self.file.name)
		if extension == '.pdf':
			return 'file-pdf text-danger'
		elif extension == '.doc' or extension == '.docx':
			return 'file-word text-info'
		elif extension == '.xls' or extension == '.xlsx':
			return 'file-excel text-success'
		elif extension == '.ppt' or extension == '.pptx':
			return 'file-powerpoint text-warning'
		elif extension == '.jpg' or extension == '.png':
			return 'file-image text-primary'
		else:
			return 'file text-muted'

	def get_absolute_url(self):
		return reverse('report-update', kwargs={'pk': self.pk})

administrator/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Staff, Student
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, HTML, Submit, ButtonHolder

class UserAddForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['email'].required=True
		self.helper = FormHelper()
		self.helper.form_tag = False

class StaffCreateForm(forms.ModelForm):
	class Meta:
		model = Staff
		fields = '__all__'

	birthdate = forms.DateField(
	widget=forms.TextInput(
		attrs={'type': 'date'}
		)
	)
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.fields['image'].required = False


class StudentCreateForm(forms.ModelForm):
	class Meta:
		model = Student
		fields = '__all__'

	birthdate = forms.DateField(
	widget=forms.TextInput(
		attrs={'type': 'date'}
		)
	)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_tag = False

administrator/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView,
	)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.admin.models import LogEntry
from django.db.models import Q

# Create your views here.
class StudentCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
	model = Student
	form_class = StudentCreateForm
	success_message = "Student added successfully."
	template_name = 'administrator/student_create.html'

	def form_valid(self, form):
		messages.success(self.request, self.success_message)
		return super().form_valid(form)

class StudentUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	model = Student
	fields = '__all__'
	success_message = "Student updated successfully."

class StudentListView(LoginRequiredMixin, ListView):
	model = Student
	paginate_by = 10
	# ordering = ['section__grade_level', 'section__name', 'last_name']

	def get_queryset(self):
		query = self.request.GET.get('q')
		student_list = self.model.objects.all().order_by('-section__grade_level')
		if query is not None:
			student_list = student_list.filter(
			Q(first_name__icontains=query) |
			Q(middle_name__icontains=query) |
			Q(last_name__icontains=query) |
			Q(lrn__icontains=query)
			)
		return student_list

# class StudentBulkDeleteView(View):
#     model = Student
#
#     def post(self, request, *args, **kwargs):
#         delete_ids = request.POST['delete_ids'].split(',')  # should validate
#         self.model.objects.filter(pk__in=delete_ids).delete()
#         return reverse_lazy('student-list')

class ReportListView(LoginRequiredMixin, ListView):
	model = Report
	context_object_name = 'reports'
	ordering = ['-month_year']

class ReportUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	model = Report
	fields = ['title', 'remarks', 'file', 'month_year']
	success_message = 'Report updated successfully.'

class StudentDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
	model = Student
	success_url = reverse_lazy('student-list')
	success_message = "Student deleted successfully."

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(StudentDeleteView, self).delete(request, *args, **kwargs)

class LogEntryListView(LoginRequiredMixin, ListView):
	model = LogEntry
	context_object_name = 'actions'
	template_name = "administrator/logentry_list.html"
	ordering = ['-action_time']
	paginate_by = 10

class PostListView(LoginRequiredMixin, ListView):
	model = Post
	context_object_name = 'posts'
	ordering = ['-date_posted']

class PostCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
	model = Post
	fields = ['title', 'desc', 'image']
	success_message = "Post created successfully."
	template_name = 'administrator/post_create.html'

	def form_valid(self, form):
		form.instance.author = self.request.user
		messages.success(self.request, self.success_message)
		return super().form_valid(form)

class ReportCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
	model = Report
	fields = ['title', 'remarks', 'file', 'month_year']
	success_message = "Report uploaded successfully."
	template_name = 'administrator/report_create.html'

	def form_valid(self, form):
		form.instance.author = self.request.user
		messages.success(self.request, self.success_message)
		return super().form_valid(form)

class ReportDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
	model = Report
	success_url = reverse_lazy('report-list')
	success_message = "Report deleted successfully."

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(ReportDeleteView, self).delete(request, *args, **kwargs)

class PostUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	model = Post
	fields = ['title', 'desc', 'image']
	success_message = "Post updated successfully."

class PostDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
	model = Post
	success_url = reverse_lazy('post-list')
	success_message = "Post deleted successfully."

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(PostDeleteView, self).delete(request, *args, **kwargs)

class DashboardView(LoginRequiredMixin, ListView):
	context_object_name = 'students'
	template_name = 'administrator/dashboard.html'
	queryset = Student.objects.all()

	def get_context_data(self, **kwargs):
		context = super(ListView, self).get_context_data(**kwargs)
		context['staffs'] = Staff.objects.all()
		context['users'] = User.objects.all()
		context['reports'] = Report.objects.all()
		context['posts'] = Post.objects.all()
		return context

class StaffCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
	model = Staff
	form_class = StaffCreateForm
	template_name = 'administrator/staff_create.html'
	success_message = 'Staff profile created.'

class StaffListView(LoginRequiredMixin, ListView):
	model = Staff
	context_object_name = 'staffs'
	ordering = ['-salary']

class SectionListView(LoginRequiredMixin, ListView):
	model = Section

	def get_context_data(self, **kwargs):
		context = super(ListView, self).get_context_data(**kwargs)
		query = self.request.GET.get('SY')
		if query is None:
			sections = Section.objects.filter(term=Term.objects.latest('start_date'))
		else:
			sections = Section.objects.filter(term__title=query)
		context['terms'] = Term.objects.all().order_by('-start_date')
		context['sections']=sections
		# for i in range(0, 6):
		#     key = 'grade{}'.format(i)
		#     context[key] = sections.filter(grade_level=i)
		return context




class StaffDetailView(LoginRequiredMixin, DetailView):
	model = Staff

class StaffUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	model = Staff
	fields = ['image',
	'first_name',
	'last_name',
	'middle_name',
	'contact_number',
	'birthdate',
	'sex',
	'civil_status',
	'advisory_section',
	'position',
	'salary',
	'appointment_file',
	'pds_file',
	'prc_license_file',
	'saln_file']
	success_message = "Profile updated successfully."
	# form_class = StaffCreateForm

class StaffDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
	model = Staff
	success_url = reverse_lazy('staff-list')
	success_message = "Profile deleted successfully."

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(StaffDeleteView, self).delete(request, *args, **kwargs)

class UserCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
	model = User
	fields = ['first_name', 'last_name', 'username', 'password', 'groups']
	template_name = 'administrator/user_create.html'
	success_message = 'User created.'
	success_url = reverse_lazy('user-list')

class UserUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	model = User
	template_name = 'administrator/user_form.html'
	fields = ['first_name', 'last_name' , 'username', 'password', 'groups', 'is_active']
	success_message = 'User updated successfully.'
	success_url = reverse_lazy('user-list')

	def form_valid(self, form):
		form.instance.set_password(form.instance.password)
		return super().form_valid(form)

class UserListView(LoginRequiredMixin, ListView):
	model = User
	template_name = 'administrator/user_list.html'
	context_object_name = 'user_list'
	ordering = ['groups']

administrator/templates/administrator/dashboard.html
{%extends "administrator/base.html"%}
{%load static%}

{%block styles%}
{%endblock styles%}

{%block javascript%}
{%endblock javascript%}

{%block content%}
{%endblock content%}

administrator/templates/administrator/staff_detail.html
{%extends "administrator/base.html"%}
{%load static%}
{%load humanize%}
{%load crispy_forms_tags%}

{%block styles%}
{%endblock styles%}

{%block javascript%}
{%endblock javascript%}

{%block breadcrumbs%}
<div class="container mt-2">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{%url 'dashboard'%}">Admin</a></li>
      <li class="breadcrumb-item"><a href="{%url 'staff-list'%}">Manage Staff</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{object.first_name}}'s Profile</li>
    </ol>
  </nav>
</div>
{%endblock breadcrumbs%}

{%block content%}

<div class="container wow fadeIn">
  <div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
          <form method="post" action="{%url 'staff-delete' object.pk%}">
          {%csrf_token%}
          <div class="modal-header">
            <h5 class="modal-title">Delete Staff</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <h6>Are you sure you want to delete {{object.first_name}}'s profile?</h6>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-muted" data-dismiss="modal">Close</button>
            <input type="submit" class="btn btn-danger" name="submit" value="Delete">
          </div>

        </form>

      </div>
    </div>
  </div>
  <span class="display-4 font-weight-bold mt-4">
    staff profile
  </span>
  <div class="row no-gutters border rounded shadow-sm">
    <div class="col-3 text-center">
      <img class="img-fluid border rounded-circle" src="{{object.image.url}}" alt="{{object.first_name}}'s Photo">
      <div>
        <a href="{%url 'staff-update' staff.id%}" class="btn btn-primary mt-2"><i class="fas fa-user-edit fa-lg"></i></a>
        <button class="btn btn-danger mt-2" data-toggle="modal" data-target="#modal"><i class=" fas fa-user-times fa-lg"></i></button>
      </div>

    </div>
    <div class="col-9">
      <h3>{{object.last_name}}, {{object.first_name}} {{object.middle_name|default_if_none:""}}</h3>
      <span class="bg-info text-white rounded p-1"><i class="fas fa-user-tie"></i> {{object.position}}</span>
      <span class="bg-success text-white rounded p-1"><i class="fas fa-money-check-alt"></i> PHP{{object.salary|intcomma}}</span>
      {%if object.advisory_section%}
      <span class="bg-primary text-white rounded p-1"><i class="fas fa-chalkboard-teacher"></i> {{object.advisory_section}}</span>
      {%endif%}
      <hr>
      <h5><strong><i class="fas fa-info-circle"></i> personal information</strong></h5>
      <dl class="row">
        <dt class="col-sm-3">Sex</dt>
        <dd class="col-sm-3">{{object.get_sex_display}}</dd>
        <dt class="col-sm-3">Age</dt>
        <dd class="col-sm-3">{{object.calculate_age}}</dd>
        <dt class="col-sm-3">Birthdate</dt>
        <dd class="col-sm-3">{{object.birthdate}}</dd>
        <dt class="col-sm-3">Civil Status</dt>
        <dd class="col-sm-3">{{object.get_civil_status_display}}</dd>
      </dl>
      <hr>
      <h5><strong><i class="fas fa-envelope"></i> contact details</strong></h5>
      <dl class="row">
        <dt class="col-sm-3">Email address</dt>
        <dd class="col-sm-3">{{object.email_address}}</dd>
        <dt class="col-sm-3">Contact Number</dt>
        <dd class="col-sm-3">{{object.contact_number}}</dd>
      </dl>
      <hr>
      <h5><strong><i class="fas fa-file-alt"></i> documents</strong></h5>
      <div class="row">
        {%if not object.appointment_file and not object.pds_file and not object.prc_license_file and not object.saln_file%}
        <div class="col-12 text-center">
          <p class="text-muted">No files uploaded yet. Please upload documents using the Edit Profile page.</p>
        </div>
        {%else%}
        {%if object.appointment_file%}
        <div class="col-6 text-center">
          <a href="{{object.appointment_file.url}}">
            <i class="fas fa-file-contract fa-4x"></i>
            <h5>Appointment File</h5>
          </a>
        </div>
        {%endif%}
        {%if object.pds_file%}
        <div class="col-6 text-center">
          <a href="{{object.pds_file.url}}">
            <i class="fas fa-file-alt fa-4x"></i>
            <h5>Personal Data Sheet</h5>
          </a>
        </div>
        {%endif%}

        {%if object.prc_license_file%}
        <div class="col-6 text-center">
          <a href="{{object.prc_license_file.url}}">
            <i class="fas fa-id-card fa-4x"></i>
            <h5>PRC License</h5>
          </a>
        </div>
        {%endif%}

        {%if object.saln_file%}
        <div class="col-6 text-center">
          <a href="{{object.saln_file.url}}">
            <i class="fas fa-file-invoice-dollar fa-4x"></i>
            <h5>SALN File</h5>
          </a>
        </div>
        {%endif%}
        {%endif%}
      </div>
    </div>
  </div>
</div>
{%endblock content%}

administrator/templates/administrator/student_list.html
{%extends "administrator/base.html"%}
{%load static%}
{%load crispy_forms_tags%}

{%block styles%}
{%endblock styles%}

{%block javascript%}
<script>
  jQuery(document).ready(function($) {
    $('#checkAll').click(function () {
     $('.student-checkbox').prop('checked', this.checked);
 });
  });
</script>
{%endblock javascript%}

{%block breadcrumbs%}
{%endblock breadcrumbs%}

{%block content%}
<div class="container wow fadeIn">
  <span class="align-middle display-4 font-weight-bold mt-4">
    students
  </span>
  <a href="{%url 'student-create' %}" class="align-middle btn btn-outline-success">add new</a>
  <hr>
  <form method="GET" action="" class="form-inline">
    <div class="input-group">
      <select class="form-control" id="inputGroupSelect04" aria-label="Example select with button addon">
        <option selected>actions</option>
        <option value="1">transfer</option>
        <option value="2">delete</option>
        <option value="3">generate blank SF9</option>
        <option value="4">generate blank SF10</option>
        <option value="5">print</option>
      </select>
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit"><i class="fa fa-chevron-right"></i></button>
      </div>
    </div>

    <div class="input-group ml-auto">
      <a href="{%url 'student-list'%}" class="btn btn-outline-secondary mr-2">reset search </a>
      <div class="input-group">
        <input type="text" class="form-control" name="q" placeholder="search by LRN or name" aria-label="search" aria-describedby="button-addon2">
        <div class="input-group-append">
          <button class="btn btn-success" type="submit" id="button-addon2"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div>



  <div class="row">
    <div class="col-12">
      <table class="table table-hover shadow-sm">
        <caption>Click anywhere in a row to to edit the corresponding student's information.</caption>
        <thead class="bg-success text-white">
          <tr>
            <th scope="col"><input id="checkAll" type="checkbox"></th>
            <th scope="col">LRN</th>
            <th scope="col">Full Name</th>
            <th scope="col">Sex</th>
            <th scope="col">Age</th>
            <th scope="col">Grade & Section</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {%for student in student_list%}
          <tr class="clickable-row" data-href='{%url 'student-update' student.pk%}'>
            <th><input value="{{student.pk}} " class="student-checkbox" type="checkbox"></th>
            <th scope="row">{{student.lrn}}</th>
            <td>{{student}}</td>
            <td>{{student.get_sex_display}}</td>
            <td>{{student.calculate_age}}</td>
            <td>{{student.section}}</td>
            <td><a href="{%url 'student-update' student.pk%}"><i class="fa fa-edit"></i></a> <a href="{%url 'student-delete' student.pk%}"><i class="fa fa-trash text-danger"></i></a> </td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
      </form>
      
      {% if is_paginated %}
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1" tabindex="-1"><i class="fas fa-angle-double-left"></i></a></li>
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1"><i class="fas fa-angle-left"></i></a></li>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <li class="page-item"><a class="page-link" href="?page={{ num }}">{{num}}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <li class="page-item"><a class="page-link" href="?page={{ num }}">{{num}}</a></li>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fas fa-angle-right"></i></a></li>
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-angle-double-right"></i></a></li>
          {% endif %}

        </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>
{%endblock content%}